In [1]:
import pandas as pd
import os

# Dataset path
DATASET_PATH = "../DATA_SET/Crop recommendation dataset.csv"

# Load dataset
df = pd.read_csv(DATASET_PATH)

print("=" * 70)
print("SMART FARMING - DATASET INSPECTION")
print("=" * 70)

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nFirst 10 Rows:")
display(df.head(10))

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nStatistical Summary:")
display(df.describe(include="all").T)

======================================================================
SMART FARMING - DATASET INSPECTION
======================================================================

Dataset Shape:
(57000, 23)

Column Names:
['CROPS', 'TYPE_OF_CROP', 'SOIL', 'SEASON', 'SOWN', 'HARVESTED', 'WATER_SOURCE', 'SOIL_PH', 'SOIL_PH_HIGH', 'CROPDURATION', 'CROPDURATION_MAX', 'TEMP', 'MAX_TEMP', 'WATERREQUIRED', 'WATERREQUIRED_MAX', 'RELATIVE_HUMIDITY', 'RELATIVE_HUMIDITY_MAX', 'N', 'N_MAX', 'P', 'P_MAX', 'K', 'K_MAX']

First 10 Rows:

,CROPS,TYPE_OF_CROP,SOIL,SEASON,SOWN,HARVESTED,WATER_SOURCE,SOIL_PH,SOIL_PH_HIGH,CROPDURATION,...,WATERREQUIRED,WATERREQUIRED_MAX,RELATIVE_HUMIDITY,RELATIVE_HUMIDITY_MAX,N,N_MAX,P,P_MAX,K,K_MAX
0,rice,cereals,Alluvial soil,kharif,Jun,Sep,irrigated,7.6,8.0,116.9,...,2462.3,2500,73.8,80,82.4,100,40.7,60,42.2,60
1,rice,cereals,Loamy soil,kharif,Jul,Oct,rainfed,6.2,8.0,117.9,...,1237.5,2500,60.9,80,90.5,100,51.3,60,46.2,60
2,rice,cereals,Clay soil,kharif,Jun,Sep,irrigated,6.7,8.0,117.7,...,1075.1,2500,67.5,80,86.2,100,50.7,60,44.4,60
3,rice,cereals,Alluvial soil,kharif,Jul,Oct,rainfed,6.1,8.0,149.8,...,1549.9,2500,73.6,80,91.3,100,51.3,60,44.5,60
4,rice,cereals,Loamy soil,kharif,Jun,Sep,irrigated,8.0,8.0,131.7,...,1306.4,2500,60.3,80,81.3,100,48.6,60,51.0,60
5,rice,cereals,Clay soil,kharif,Jul,Oct,rainfed,7.9,8.0,137.7,...,1048.8,2500,60.9,80,97.6,100,40.1,60,56.3,60
6,rice,cereals,Alluvial soil,kharif,Jun,Sep,irrigated,7.3,8.0,143.3,...,1082.8,2500,70.1,80,84.2,100,54.4,60,43.0,60
7,rice,cereals,Loamy soil,kharif,Jul,Oct,rainfed,6.4,8.0,132.8,...,903.9,2500,73.4,80,96.0,100,40.2,60,52.7,60
8,rice,cereals,Clay soil,kharif,Jun,Sep,irrigated,5.6,8.0,115.8,...,1049.7,2500,76.7,80,90.7,100,48.5,60,40.4,60
9,rice,cereals,Alluvial soil,kharif,Jul,Oct,rainfed,5.9,8.0,116.9,...,1390.5,2500,73.2,80,87.6,100,59.2,60,42.5,60

Data Types:
CROPS                        str
TYPE_OF_CROP                 str
SOIL                         str
SEASON                       str
SOWN                         str
HARVESTED                    str
WATER_SOURCE                 str
SOIL_PH                  float64
SOIL_PH_HIGH             float64
CROPDURATION             float64
CROPDURATION_MAX           int64
TEMP                     float64
MAX_TEMP                   int64
WATERREQUIRED            float64
WATERREQUIRED_MAX          int64
RELATIVE_HUMIDITY        float64
RELATIVE_HUMIDITY_MAX      int64
N                        float64
N_MAX                      int64
P                        float64
P_MAX                      int64
K                        float64
K_MAX                      int64
dtype: object

Missing Values:
CROPS                    0
TYPE_OF_CROP             0
SOIL                     0
SEASON                   0
SOWN                     0
HARVESTED                0
WATER_SOURCE             0
SOIL_PH                  0
SOIL_PH_HIGH             0
CROPDURATION             0
CROPDURATION_MAX         0
TEMP                     0
MAX_TEMP                 0
WATERREQUIRED            0
WATERREQUIRED_MAX        0
RELATIVE_HUMIDITY        0
RELATIVE_HUMIDITY_MAX    0
N                        0
N_MAX                    0
P                        0
P_MAX                    0
K                        0
K_MAX                    0
dtype: int64

Duplicate Rows:
0

Statistical Summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
CROPS,57000,57,rice,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TYPE_OF_CROP,57000,10,vegetables,22000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SOIL,57000,34,sandy Loamy soil,15332,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SEASON,57000,3,Zaid,23000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SOWN,57000,8,Jun,14100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HARVESTED,57000,7,Apr,9610,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WATER_SOURCE,57000,2,irrigated,31500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SOIL_PH,57000.0,NaN,NaN,NaN,6.624367,0.649972,5.0,6.2,6.6,7.0,9.0
SOIL_PH_HIGH,57000.0,NaN,NaN,NaN,7.245614,0.60931,6.0,6.8,7.0,7.5,9.0
CROPDURATION,57000.0,NaN,NaN,NaN,109.347488,52.931444,21.0,75.9,99.9,120.5,330.0
CROPDURATION_MAX,57000.0,NaN,NaN,NaN,117.736842,54.934103,21.0,90.0,105.0,140.0,330.0
TEMP,57000.0,NaN,NaN,NaN,24.75774,5.862506,5.0,21.1,24.8,28.0,47.0
MAX_TEMP,57000.0,NaN,NaN,NaN,30.385965,6.354373,18.0,27.0,30.0,35.0,47.0
WATERREQUIRED,57000.0,NaN,NaN,NaN,887.262882,356.326523,330.0,604.6,929.5,1070.1,2499.8
WATERREQUIRED_MAX,57000.0,NaN,NaN,NaN,1038.596491,438.103562,350.0,750.0,1000.0,1200.0,2500.0
RELATIVE_HUMIDITY,57000.0,NaN,NaN,NaN,71.197588,23.158554,15.0,64.4,78.2,85.3,100.0
RELATIVE_HUMIDITY_MAX,57000.0,NaN,NaN,NaN,76.421053,23.860877,18.0,70.0,85.0,90.0,100.0
N,57000.0,NaN,NaN,NaN,81.284277,33.786202,20.0,56.6,80.5,100.8,199.9
N_MAX,57000.0,NaN,NaN,NaN,98.947368,37.542549,40.0,80.0,100.0,120.0,200.0
P,57000.0,NaN,NaN,NaN,48.197891,17.160902,20.0,34.975,47.7,58.0,100.0
P_MAX,57000.0,NaN,NaN,NaN,60.526316,19.414494,30.0,40.0,60.0,80.0,100.0
K,57000.0,NaN,NaN,NaN,56.605086,27.438288,20.0,34.9,50.5,75.4,149.9
K_MAX,57000.0,NaN,NaN,NaN,69.122807,30.681465,30.0,40.0,60.0,100.0,150.0

In [2]:
print("=" * 70)
print("UNIQUE VALUES FOR EACH COLUMN")
print("=" * 70)

for column in df.columns:
    print(f"\n{column}")
    print("-" * 40)
    print("Unique values:", df[column].nunique())

    if df[column].nunique() <= 30:
        print(df[column].unique())

======================================================================
UNIQUE VALUES FOR EACH COLUMN
======================================================================

CROPS
----------------------------------------
Unique values: 57

TYPE_OF_CROP
----------------------------------------
Unique values: 10
<StringArray>
[       'cereals',        'millets',         'pulses',      'oil seeds',
     'fibre crop',    'sugar crops',     'vegetables',      'colecrops',
     'Root&tuber', 'bulbvegetables']
Length: 10, dtype: str

SOIL
----------------------------------------
Unique values: 34

SEASON
----------------------------------------
Unique values: 3
<StringArray>
['kharif', 'rabi', 'Zaid']
Length: 3, dtype: str

SOWN
----------------------------------------
Unique values: 8
<StringArray>
['Jun', 'Jul', 'Oct', 'Nov', 'Dec', 'Mar', 'Apr', 'May']
Length: 8, dtype: str

HARVESTED
----------------------------------------
Unique values: 7
<StringArray>
['Sep', 'Oct', 'Apr', 'May', 'Jun', 'Mar', 'Jul']
Length: 7, dtype: str

WATER_SOURCE
----------------------------------------
Unique values: 2
<StringArray>
['irrigated', 'rainfed']
Length: 2, dtype: str

SOIL_PH
----------------------------------------
Unique values: 41

SOIL_PH_HIGH
----------------------------------------
Unique values: 11
[8.  7.  7.5 8.2 9.  6.5 7.8 8.5 6.8 6.7 6. ]

CROPDURATION
----------------------------------------
Unique values: 2269

CROPDURATION_MAX
----------------------------------------
Unique values: 21
[150  90 110 105  85 120  75 100  95 160 140 330 180  65  60 125  70  50
 240  21 300]

TEMP
----------------------------------------
Unique values: 418

MAX_TEMP
----------------------------------------
Unique values: 18
[40 24 27 45 29 20 42 35 30 32 47 25 26 38 31 22 21 18]

WATERREQUIRED
----------------------------------------
Unique values: 12749

WATERREQUIRED_MAX
----------------------------------------
Unique values: 16
[2500  650  800  500 1200  350  750  900 1000  700 1400  400 1300  550
 2200 1500]

RELATIVE_HUMIDITY
----------------------------------------
Unique values: 552

RELATIVE_HUMIDITY_MAX
----------------------------------------
Unique values: 15
[ 80  60  85 100  95  20  18  70  55  81  92  65  98  90  75]

N
----------------------------------------
Unique values: 1770

N_MAX
----------------------------------------
Unique values: 8
[100 120 180  80  60  40 200 150]

P
----------------------------------------
Unique values: 801

P_MAX
----------------------------------------
Unique values: 7
[ 60  90  40  30  50 100  80]

K
----------------------------------------
Unique values: 1293

K_MAX
----------------------------------------
Unique values: 9
[ 60  90  40  30  50 150  80 120 100]

In [3]:
print("=" * 70)
print("SOIL TYPE CHECK")
print("=" * 70)

soil_columns = [
    "soil_type",
    "Soil_Type",
    "soil type",
    "Soil Type",
    "soil"
]

found_soil = []

for column in soil_columns:
    if column in df.columns:
        found_soil.append(column)

if found_soil:

    print("Soil Type column found:")
    print(found_soil)

    for column in found_soil:
        print(f"\n{column} values:")
        print(df[column].value_counts())

else:

    print("NO SOIL TYPE COLUMN FOUND")
    print("\nAvailable columns are:")
    print(df.columns.tolist())

======================================================================
SOIL TYPE CHECK
======================================================================
NO SOIL TYPE COLUMN FOUND

Available columns are:
['CROPS', 'TYPE_OF_CROP', 'SOIL', 'SEASON', 'SOWN', 'HARVESTED', 'WATER_SOURCE', 'SOIL_PH', 'SOIL_PH_HIGH', 'CROPDURATION', 'CROPDURATION_MAX', 'TEMP', 'MAX_TEMP', 'WATERREQUIRED', 'WATERREQUIRED_MAX', 'RELATIVE_HUMIDITY', 'RELATIVE_HUMIDITY_MAX', 'N', 'N_MAX', 'P', 'P_MAX', 'K', 'K_MAX']

In [4]:
print("=" * 70)
print("CROP CLASSES")
print("=" * 70)

possible_crop_columns = [
    "crop",
    "Crop",
    "label",
    "Label",
    "crop_name",
    "Crop_Name"
]

for column in possible_crop_columns:

    if column in df.columns:

        print("Crop column:", column)
        print("\nNumber of classes:", df[column].nunique())

        print("\nCrop distribution:")
        display(df[column].value_counts())

        break

======================================================================
CROP CLASSES
======================================================================

In [5]:
print("=" * 70)
print("CATEGORICAL COLUMN VALUES")
print("=" * 70)

categorical_columns = [
    "CROPS",
    "TYPE_OF_CROP",
    "SOIL",
    "SEASON",
    "SOWN",
    "HARVESTED",
    "WATER_SOURCE"
]

for column in categorical_columns:
    print(f"\n{'=' * 50}")
    print(f"{column}")
    print(f"{'=' * 50}")
    print("Unique values:", df[column].nunique())
    print(df[column].dropna().unique()[:100])

======================================================================
CATEGORICAL COLUMN VALUES
======================================================================

==================================================
CROPS
==================================================
Unique values: 57
<StringArray>
[             'rice',             'wheat',             'maize',
           'sorghum',      'Pearl millet',              'ragi',
        'panivaragu',             'samai',            'thinai',
            'varagu',       'kudiraivali',         'blackgram',
         'greengram',            'cowpea',        'bengalgram',
         'horsegram',           'redgram',          'soyabean',
         'groundnut',         'sunflower',           'gingely',
            'castor',            'cotton',              'jute',
         'sugarcane',         'sugarbeet',            'tomato',
             'onion',          'chillies',           'Cabbage',
            'bhendi',           'brinjal',          'capsicum',
           'pumpkin',       'snake gourd',      'ribbed gourd',
      'bottle gourd',      'bitter gourd',         'ash gourd',
          'cucumber',        'watermelon',         'muskmelon',
             'tinda',          'chowchow',      'cluster bean',
  'vegetable cowpea',       'french bean',              'peas',
    'annual moringa',            'carrot',          'beetroot',
            'radish',      'sweet potato',           'tapoica',
 'elephant foot yam',       'cauliflower',       'small onion']
Length: 57, dtype: str

==================================================
TYPE_OF_CROP
==================================================
Unique values: 10
<StringArray>
[       'cereals',        'millets',         'pulses',      'oil seeds',
     'fibre crop',    'sugar crops',     'vegetables',      'colecrops',
     'Root&tuber', 'bulbvegetables']
Length: 10, dtype: str

==================================================
SOIL
==================================================
Unique values: 34
<StringArray>
[                     'Alluvial soil',                         'Loamy soil',
                          'Clay soil',                  'well-drained soil',
                           'Red soil',                    'clay Loamy soil',
                   'sandy loamy soil',                         'Black Soil',
                         'Sandy soil',                 'shallow Black Soil',
                   'sandy Loamy soil',                  'black cotton soil',
                         'Sandy soil',                       ' cotton soil',
                        'Sandy soil ',                  'medium Black Soil',
                   'heavy Black Soil',                         ' light soi',
                        'heavy soil ',                          'deep soil',
                         'loamy soil',             'sandy clay Loamy soil ',
                   'silty Loamy soil',              'salty clay Loamy soil',
                     'red Loamy soil',                   'brown Loamy soil',
                   'clay Loamy soil ',                      'Laterite soil',
            'well-drained loamy soil',                   'light Loamy soil',
                       'friable soil', 'well-grained deep loamy moist soil',
           'red lateritic Loamy soil',                'rich red Loamy soil']
Length: 34, dtype: str

==================================================
SEASON
==================================================
Unique values: 3
<StringArray>
['kharif', 'rabi', 'Zaid']
Length: 3, dtype: str

==================================================
SOWN
==================================================
Unique values: 8
<StringArray>
['Jun', 'Jul', 'Oct', 'Nov', 'Dec', 'Mar', 'Apr', 'May']
Length: 8, dtype: str

==================================================
HARVESTED
==================================================
Unique values: 7
<StringArray>
['Sep', 'Oct', 'Apr', 'May', 'Jun', 'Mar', 'Jul']
Length: 7, dtype: str

==================================================
WATER_SOURCE
==================================================
Unique values: 2
<StringArray>
['irrigated', 'rainfed']
Length: 2, dtype: str

In [6]:
print("=" * 70)
print("NUMERICAL DATA SUMMARY")
print("=" * 70)

numeric_columns = [
    "SOIL_PH",
    "SOIL_PH_HIGH",
    "CROPDURATION",
    "CROPDURATION_MAX",
    "TEMP",
    "MAX_TEMP",
    "WATERREQUIRED",
    "WATERREQUIRED_MAX",
    "RELATIVE_HUMIDITY",
    "RELATIVE_HUMIDITY_MAX",
    "N",
    "N_MAX",
    "P",
    "P_MAX",
    "K",
    "K_MAX"
]

display(df[numeric_columns].describe().T)

======================================================================
NUMERICAL DATA SUMMARY
======================================================================

,count,mean,std,min,25%,50%,75%,max
SOIL_PH,57000.0,6.624367,0.649972,5.0,6.200,6.6,7.0,9.0
SOIL_PH_HIGH,57000.0,7.245614,0.609310,6.0,6.800,7.0,7.5,9.0
CROPDURATION,57000.0,109.347488,52.931444,21.0,75.900,99.9,120.5,330.0
CROPDURATION_MAX,57000.0,117.736842,54.934103,21.0,90.000,105.0,140.0,330.0
TEMP,57000.0,24.757740,5.862506,5.0,21.100,24.8,28.0,47.0
MAX_TEMP,57000.0,30.385965,6.354373,18.0,27.000,30.0,35.0,47.0
WATERREQUIRED,57000.0,887.262882,356.326523,330.0,604.600,929.5,1070.1,2499.8
WATERREQUIRED_MAX,57000.0,1038.596491,438.103562,350.0,750.000,1000.0,1200.0,2500.0
RELATIVE_HUMIDITY,57000.0,71.197588,23.158554,15.0,64.400,78.2,85.3,100.0
RELATIVE_HUMIDITY_MAX,57000.0,76.421053,23.860877,18.0,70.000,85.0,90.0,100.0
N,57000.0,81.284277,33.786202,20.0,56.600,80.5,100.8,199.9
N_MAX,57000.0,98.947368,37.542549,40.0,80.000,100.0,120.0,200.0
P,57000.0,48.197891,17.160902,20.0,34.975,47.7,58.0,100.0
P_MAX,57000.0,60.526316,19.414494,30.0,40.000,60.0,80.0,100.0
K,57000.0,56.605086,27.438288,20.0,34.900,50.5,75.4,149.9
K_MAX,57000.0,69.122807,30.681465,30.0,40.000,60.0,100.0,150.0

In [7]:
print("=" * 70)
print("CROP DISTRIBUTION")
print("=" * 70)

print("Number of crop classes:", df["CROPS"].nunique())

display(
    df["CROPS"]
    .value_counts()
    .to_frame("Count")
)

======================================================================
CROP DISTRIBUTION
======================================================================
Number of crop classes: 57

                   Count
CROPS
rice                1000
wheat               1000
maize               1000
sorghum             1000
Pearl millet        1000
ragi                1000
panivaragu          1000
samai               1000
thinai              1000
varagu              1000
kudiraivali         1000
blackgram           1000
greengram           1000
cowpea              1000
bengalgram          1000
horsegram           1000
redgram             1000
soyabean            1000
groundnut           1000
sunflower           1000
gingely             1000
castor              1000
cotton              1000
jute                1000
sugarcane           1000
sugarbeet           1000
tomato              1000
onion               1000
chillies            1000
Cabbage             1000
bhendi              1000
brinjal             1000
capsicum            1000
pumpkin             1000
snake gourd         1000
ribbed gourd        1000
bottle gourd        1000
bitter gourd        1000
ash gourd           1000
cucumber            1000
watermelon          1000
muskmelon           1000
tinda               1000
chowchow            1000
cluster bean        1000
vegetable cowpea    1000
french bean         1000
peas                1000
annual moringa      1000
carrot              1000
beetroot            1000
radish              1000
sweet potato        1000
tapoica             1000
elephant foot yam   1000
cauliflower         1000
small onion         1000

In [9]:
print("SOIL TYPES IN THE DATASET")
print("=" * 50)

soil_types = df["SOIL"].dropna().unique()

print("Number of soil types:", len(soil_types))
print("\nSoil types:")

for i, soil in enumerate(soil_types, 1):
    print(f"{i}. {soil}")

print("SOIL TYPE DISTRIBUTION")
print("=" * 50)

print(df["SOIL"].value_counts())

SOIL TYPES IN THE DATASET
==================================================
Number of soil types: 34

Soil types:
1. Alluvial soil
2. Loamy soil
3. Clay soil
4. well-drained soil
5. Red soil
6. clay Loamy soil
7. sandy loamy soil
8. Black Soil
9. Sandy soil
10. shallow Black Soil
11. sandy Loamy soil
12. black cotton soil
13. Sandy soil
14.  cotton soil
15. Sandy soil
16. medium Black Soil
17. heavy Black Soil
18.  light soi
19. heavy soil
20. deep soil
21. loamy soil
22. sandy clay Loamy soil
23. silty Loamy soil
24. salty clay Loamy soil
25. red Loamy soil
26. brown Loamy soil
27. clay Loamy soil
28. Laterite soil
29. well-drained loamy soil
30. light Loamy soil
31. friable soil
32. well-grained deep loamy moist soil
33. red lateritic Loamy soil
34. rich red Loamy soil
SOIL TYPE DISTRIBUTION
==================================================
SOIL
sandy Loamy soil                      15332
Loamy soil                            10283
well-drained soil                      3836
Laterite soil                          3500
Sandy soil                             2033
well-drained loamy soil                2000
clay Loamy soil                        1833
Alluvial soil                          1667
Clay soil                              1667
Red soil                               1533
loamy soil                             1000
friable soil                           1000
red lateritic Loamy soil               1000
rich red Loamy soil                    1000
black cotton soil                       750
silty Loamy soil                        750
salty clay Loamy soil                   750
Black Soil                              534
Sandy soil                              500
 cotton soil                            500
medium Black Soil                       500
heavy Black Soil                        500
 light soi                              500
heavy soil                              500
deep soil                               500
light Loamy soil                        500
well-grained deep loamy moist soil      500
sandy loamy soil                        333
Sandy soil                              333
sandy clay Loamy soil                   333
clay Loamy soil                         333
red Loamy soil                          250
brown Loamy soil                        250
shallow Black Soil                      200
Name: count, dtype: int64

In [10]:


# Clean SOIL values
df["SOIL_CLEAN"] = (
    df["SOIL"]
    .astype(str)
    .str.replace("\u00a0", " ", regex=False)  # Remove non-breaking spaces
    .str.strip()                              # Remove leading/trailing spaces
    .str.lower()                              # Convert to lowercase
    .str.replace(r"\s+", " ", regex=True)     # Remove duplicate spaces
)

print("RAW SOIL TYPES :", df["SOIL"].nunique())
print("CLEAN SOIL TYPES:", df["SOIL_CLEAN"].nunique())

print("\nCLEAN SOIL TYPES")
print("=" * 50)

for i, soil in enumerate(sorted(df["SOIL_CLEAN"].unique()), 1):
    print(f"{i}. {soil}")

RAW SOIL TYPES : 34
CLEAN SOIL TYPES: 29

CLEAN SOIL TYPES
==================================================
1. alluvial soil
2. black cotton soil
3. black soil
4. brown loamy soil
5. clay loamy soil
6. clay soil
7. cotton soil
8. deep soil
9. friable soil
10. heavy black soil
11. heavy soil
12. laterite soil
13. light loamy soil
14. light soi
15. loamy soil
16. medium black soil
17. red lateritic loamy soil
18. red loamy soil
19. red soil
20. rich red loamy soil
21. salty clay loamy soil
22. sandy clay loamy soil
23. sandy loamy soil
24. sandy soil
25. shallow black soil
26. silty loamy soil
27. well-drained loamy soil
28. well-drained soil
29. well-grained deep loamy moist soil

In [11]:
print("CLEAN SOIL TYPE DISTRIBUTION")
print("=" * 50)

print(df["SOIL_CLEAN"].value_counts())

CLEAN SOIL TYPE DISTRIBUTION
==================================================
SOIL_CLEAN
sandy loamy soil                      15665
loamy soil                            11283
well-drained soil                      3836
laterite soil                          3500
sandy soil                             2866
clay loamy soil                        2166
well-drained loamy soil                2000
alluvial soil                          1667
clay soil                              1667
red soil                               1533
friable soil                           1000
red lateritic loamy soil               1000
rich red loamy soil                    1000
black cotton soil                       750
silty loamy soil                        750
salty clay loamy soil                   750
black soil                              534
cotton soil                             500
medium black soil                       500
heavy black soil                        500
light soi                               500
heavy soil                              500
deep soil                               500
light loamy soil                        500
well-grained deep loamy moist soil      500
sandy clay loamy soil                   333
red loamy soil                          250
brown loamy soil                        250
shallow black soil                      200
Name: count, dtype: int64

In [12]:
categorical_columns = [
    "CROPS",
    "TYPE_OF_CROP",
    "SOIL",
    "SEASON",
    "SOWN",
    "HARVESTED",
    "WATER_SOURCE"
]

for col in categorical_columns:
    print("\n" + "=" * 60)
    print(f"{col}")
    print("=" * 60)
    print("Unique values:", df[col].nunique())
    print(df[col].dropna().unique())

============================================================
CROPS
============================================================
Unique values: 57
<StringArray>
[             'rice',             'wheat',             'maize',
           'sorghum',      'Pearl millet',              'ragi',
        'panivaragu',             'samai',            'thinai',
            'varagu',       'kudiraivali',         'blackgram',
         'greengram',            'cowpea',        'bengalgram',
         'horsegram',           'redgram',          'soyabean',
         'groundnut',         'sunflower',           'gingely',
            'castor',            'cotton',              'jute',
         'sugarcane',         'sugarbeet',            'tomato',
             'onion',          'chillies',           'Cabbage',
            'bhendi',           'brinjal',          'capsicum',
           'pumpkin',       'snake gourd',      'ribbed gourd',
      'bottle gourd',      'bitter gourd',         'ash gourd',
          'cucumber',        'watermelon',         'muskmelon',
             'tinda',          'chowchow',      'cluster bean',
  'vegetable cowpea',       'french bean',              'peas',
    'annual moringa',            'carrot',          'beetroot',
            'radish',      'sweet potato',           'tapoica',
 'elephant foot yam',       'cauliflower',       'small onion']
Length: 57, dtype: str

============================================================
TYPE_OF_CROP
============================================================
Unique values: 10
<StringArray>
[       'cereals',        'millets',         'pulses',      'oil seeds',
     'fibre crop',    'sugar crops',     'vegetables',      'colecrops',
     'Root&tuber', 'bulbvegetables']
Length: 10, dtype: str

============================================================
SOIL
============================================================
Unique values: 34
<StringArray>
[                     'Alluvial soil',                         'Loamy soil',
                          'Clay soil',                  'well-drained soil',
                           'Red soil',                    'clay Loamy soil',
                   'sandy loamy soil',                         'Black Soil',
                         'Sandy soil',                 'shallow Black Soil',
                   'sandy Loamy soil',                  'black cotton soil',
                         'Sandy soil',                       ' cotton soil',
                        'Sandy soil ',                  'medium Black Soil',
                   'heavy Black Soil',                         ' light soi',
                        'heavy soil ',                          'deep soil',
                         'loamy soil',             'sandy clay Loamy soil ',
                   'silty Loamy soil',              'salty clay Loamy soil',
                     'red Loamy soil',                   'brown Loamy soil',
                   'clay Loamy soil ',                      'Laterite soil',
            'well-drained loamy soil',                   'light Loamy soil',
                       'friable soil', 'well-grained deep loamy moist soil',
           'red lateritic Loamy soil',                'rich red Loamy soil']
Length: 34, dtype: str

============================================================
SEASON
============================================================
Unique values: 3
<StringArray>
['kharif', 'rabi', 'Zaid']
Length: 3, dtype: str

============================================================
SOWN
============================================================
Unique values: 8
<StringArray>
['Jun', 'Jul', 'Oct', 'Nov', 'Dec', 'Mar', 'Apr', 'May']
Length: 8, dtype: str

============================================================
HARVESTED
============================================================
Unique values: 7
<StringArray>
['Sep', 'Oct', 'Apr', 'May', 'Jun', 'Mar', 'Jul']
Length: 7, dtype: str

============================================================
WATER_SOURCE
============================================================
Unique values: 2
<StringArray>
['irrigated', 'rainfed']
Length: 2, dtype: str

In [13]:
numeric_columns = [
    "SOIL_PH",
    "SOIL_PH_HIGH",
    "CROPDURATION",
    "CROPDURATION_MAX",
    "TEMP",
    "MAX_TEMP",
    "WATERREQUIRED",
    "WATERREQUIRED_MAX",
    "RELATIVE_HUMIDITY",
    "RELATIVE_HUMIDITY_MAX",
    "N",
    "N_MAX",
    "P",
    "P_MAX",
    "K",
    "K_MAX"
]

print("NUMERICAL COLUMN ANALYSIS")
print("=" * 70)

for col in numeric_columns:
    print(f"\n{col}")
    print("-" * 50)
    print("Minimum :", df[col].min())
    print("Maximum :", df[col].max())
    print("Mean    :", df[col].mean())
    print("Missing :", df[col].isna().sum())

NUMERICAL COLUMN ANALYSIS
======================================================================

SOIL_PH
--------------------------------------------------
Minimum : 5.0
Maximum : 9.0
Mean    : 6.624366666666667
Missing : 0

SOIL_PH_HIGH
--------------------------------------------------
Minimum : 6.0
Maximum : 9.0
Mean    : 7.245614035087719
Missing : 0

CROPDURATION
--------------------------------------------------
Minimum : 21.0
Maximum : 330.0
Mean    : 109.34748771929824
Missing : 0

CROPDURATION_MAX
--------------------------------------------------
Minimum : 21
Maximum : 330
Mean    : 117.73684210526316
Missing : 0

TEMP
--------------------------------------------------
Minimum : 5.0
Maximum : 47.0
Mean    : 24.757740350877192
Missing : 0

MAX_TEMP
--------------------------------------------------
Minimum : 18
Maximum : 47
Mean    : 30.385964912280702
Missing : 0

WATERREQUIRED
--------------------------------------------------
Minimum : 330.0
Maximum : 2499.8
Mean    : 887.2628824561403
Missing : 0

WATERREQUIRED_MAX
--------------------------------------------------
Minimum : 350
Maximum : 2500
Mean    : 1038.5964912280701
Missing : 0

RELATIVE_HUMIDITY
--------------------------------------------------
Minimum : 15.0
Maximum : 100.0
Mean    : 71.19758771929824
Missing : 0

RELATIVE_HUMIDITY_MAX
--------------------------------------------------
Minimum : 18
Maximum : 100
Mean    : 76.42105263157895
Missing : 0

N
--------------------------------------------------
Minimum : 20.0
Maximum : 199.9
Mean    : 81.28427719298247
Missing : 0

N_MAX
--------------------------------------------------
Minimum : 40
Maximum : 200
Mean    : 98.94736842105263
Missing : 0

P
--------------------------------------------------
Minimum : 20.0
Maximum : 100.0
Mean    : 48.19789122807017
Missing : 0

P_MAX
--------------------------------------------------
Minimum : 30
Maximum : 100
Mean    : 60.526315789473685
Missing : 0

K
--------------------------------------------------
Minimum : 20.0
Maximum : 149.9
Mean    : 56.605085964912284
Missing : 0

K_MAX
--------------------------------------------------
Minimum : 30
Maximum : 150
Mean    : 69.12280701754386
Missing : 0

In [14]:
print("MISSING VALUES")
print("=" * 60)

print(df.isnull().sum())

MISSING VALUES
============================================================
CROPS                    0
TYPE_OF_CROP             0
SOIL                     0
SEASON                   0
SOWN                     0
HARVESTED                0
WATER_SOURCE             0
SOIL_PH                  0
SOIL_PH_HIGH             0
CROPDURATION             0
CROPDURATION_MAX         0
TEMP                     0
MAX_TEMP                 0
WATERREQUIRED            0
WATERREQUIRED_MAX        0
RELATIVE_HUMIDITY        0
RELATIVE_HUMIDITY_MAX    0
N                        0
N_MAX                    0
P                        0
P_MAX                    0
K                        0
K_MAX                    0
SOIL_CLEAN               0
dtype: int64

In [15]:
print("DUPLICATE ROWS")
print("=" * 60)

print("Duplicate rows:", df.duplicated().sum())

DUPLICATE ROWS
============================================================
Duplicate rows: 0